export const airports = [
  { city: 'Atlanta', code: 'ATL', state: 'GA', country: '🇺🇸 United States' },
  { city: 'Chicago', code: 'ORD', state: 'IL', country: '🇺🇸 United States' },
  { city: 'Shiraz', code: 'SYZ', state: 'Fars', country: '🇮🇷 Iran' },
  { city: 'Erbil', code: 'EBL', state: 'Kurdistan', country: '🇮🇶 Iraq' },
  { city: 'Dubai', code: 'DXB', state: 'Dubai', country: '🇦🇪 United Arab Emirates' },
  { city: 'Istanbul', code: 'IST', state: 'Istanbul', country: '🇹🇷 Turkey' },
  { city: 'New York', code: 'LGA', state: 'NY', country: '🇺🇸 United States' },
  { city: 'Los Angeles', code: 'LAX', state: 'CA', country: '🇺🇸 United States' },
  { city: 'Abu Dhabi', code: 'AUH', state: 'Abu Dhabi', country: '🇦🇪 United Arab Emirates' },
  { city: 'Doha', code: 'DOH', state: 'Doha', country: '🇶🇦 Qatar' },
  { city: 'Amman', code: 'AMM', state: 'Amman', country: '🇯🇴 Jordan' },
  { city: 'Kuwait City', code: 'KWI', state: 'Kuwait', country: '🇰🇼 Kuwait' },
  { city: 'Muscat', code: 'MCT', state: 'Muscat', country: '🇴🇲 Oman' },
  { city: 'Tehran', code: 'IKA', state: 'Tehran', country: '🇮🇷 Iran' },
  { city: 'Mashhad', code: 'MHD', state: 'Khorasan', country: '🇮🇷 Iran' },
  { city: 'Ankara', code: 'ESB', state: 'Ankara', country: '🇹🇷 Turkey' },
  { city: 'Riyadh', code: 'RUH', state: 'Riyadh', country: '🇸🇦 Saudi Arabia' },
  { city: 'Jeddah', code: 'JED', state: 'Mecca', country: '🇸🇦 Saudi Arabia' },
  { city: 'Manama', code: 'BAH', state: 'Capital', country: '🇧🇭 Bahrain' },
  { city: 'Tel Aviv', code: 'TLV', state: 'Tel Aviv', country: '🇮🇱 Israel' },
  { city: 'Baghdad', code: 'BGW', state: 'Baghdad', country: '🇮🇶 Iraq' },
  { city: 'Basra', code: 'BSR', state: 'Basra', country: '🇮🇶 Iraq' },
  { city: 'Dushanbe', code: 'DYU', state: 'Dushanbe', country: '🇹🇯 Tajikistan' },
  { city: 'Khujand', code: 'LBD', state: 'Sughd', country: '🇹🇯 Tajikistan' },
  { city: 'New York', code: 'JFK', state: 'NY', country: '🇺🇸 United States' },
  { city: 'San Francisco', code: 'SFO', state: 'CA', country: '🇺🇸 United States' },
  { city: 'San Diego', code: 'SAN', state: 'CA', country: '🇺🇸 United States' },
  { city: 'Dallas', code: 'DFW', state: 'TX', country: '🇺🇸 United States' },
  { city: 'Houston', code: 'IAH', state: 'TX', country: '🇺🇸 United States' },
  { city: 'Miami', code: 'MIA', state: 'FL', country: '🇺🇸 United States' },
  { city: 'Orlando', code: 'MCO', state: 'FL', country: '🇺🇸 United States' },
  { city: 'Seattle', code: 'SEA', state: 'WA', country: '🇺🇸 United States' },
  { city: 'Boston', code: 'BOS', state: 'MA', country: '🇺🇸 United States' },
  { city: 'Las Vegas', code: 'LAS', state: 'NV', country: '🇺🇸 United States' },
  { city: 'Denver', code: 'DEN', state: 'CO', country: '🇺🇸 United States' },
  { city: 'Phoenix', code: 'PHX', state: 'AZ', country: '🇺🇸 United States' },
  { city: 'London', code: 'LHR', state: 'London', country: '🇬🇧 United Kingdom' },
  { city: 'London', code: 'LGW', state: 'London', country: '🇬🇧 United Kingdom' },
  { city: 'Paris', code: 'CDG', state: 'Paris', country: '🇫🇷 France' },
  { city: 'Frankfurt', code: 'FRA', state: 'Hesse', country: '🇩🇪 Germany' },
  { city: 'Munich', code: 'MUC', state: 'Bavaria', country: '🇩🇪 Germany' },
  { city: 'Amsterdam', code: 'AMS', state: 'North Holland', country: '🇳🇱 Netherlands' },
  { city: 'Madrid', code: 'MAD', state: 'Madrid', country: '🇪🇸 Spain' },
  { city: 'Barcelona', code: 'BCN', state: 'Catalonia', country: '🇪🇸 Spain' },
  { city: 'Rome', code: 'FCO', state: 'Lazio', country: '🇮🇹 Italy' },
  { city: 'Milan', code: 'MXP', state: 'Lombardy', country: '🇮🇹 Italy' },
  { city: 'Istanbul', code: 'SAW', state: 'Istanbul', country: '🇹🇷 Turkey' },
  { city: 'Zurich', code: 'ZRH', state: 'Zurich', country: '🇨🇭 Switzerland' },
  { city: 'Vienna', code: 'VIE', state: 'Vienna', country: '🇦🇹 Austria' }
];